separator=false
interval=1

[date]
command=/home/cameron/.config/sway/bar/scripts/date.sh
separator_block_width=170

[memory]
command=/home/cameron/.config/sway/bar/scripts/memory.sh
separator_block_width=190

[time]
command=/home/cameron/.config/sway/bar/scripts/time.sh
separator_block_width=325

[volume]
command=/home/cameron/.config/sway/bar/scripts/volume.sh
separator_block_width=120
signal=1

#[audio output]
#full_text=[ ♫ ]
#interval=persist
#command=while read button; do pavucontrol; done
#separator_block_width=220

[network]
command=/home/cameron/.config/sway/bar/scripts/network_connected.sh
separator_block_width=120
markup=pango

[battery]
command=/home/cameron/.config/sway/bar/scripts/battery.sh
markup=pango
separator_block_width=0
