separator=false
interval=1

[date]
command=/home/cameron/.config/sway/bar/scripts/date.sh
separator_block_width=150
markup=pango

[memory]
command=/home/cameron/.config/sway/bar/scripts/memory.sh
separator_block_width=150
markup=pango

[time]
command=/home/cameron/.config/sway/bar/scripts/time.sh
separator_block_width=210
markup=pango

[audio output]
full_text=[ ♫ ]
interval=persist
command=while read button; do pavucontrol; done
separator_block_width=0
markup=pango

[volume]
command=/home/cameron/.config/sway/bar/scripts/volume.sh
separator_block_width=90
signal=1
markup=pango

[network]
command=/home/cameron/.config/sway/bar/scripts/network_connected.sh
separator_block_width=20
markup=pango

[battery]
command=/home/cameron/.config/sway/bar/scripts/battery.sh
markup=pango
separator_block_width=0
