separator=false
interval=1

[date]
command=/home/cameron/.config/sway/bar/scripts/date.sh
separator_block_width=500

[time]
command=/home/cameron/.config/sway/bar/scripts/time.sh
separator_block_width=325

[volume]
command=/home/cameron/.config/sway/bar/scripts/volume.sh
separator_block_width=5
signal=1

[audio output]
full_text=[ ♫ ]
interval=persist
command=while read button; do pavucontrol; done
separator_block_width=220

[battery]
command=/home/cameron/.config/sway/bar/scripts/battery.sh
markup=pango
separator_block_width=0
